/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.ControladorCine;
import Modelo.Cine;
import Modelo.FuncionCine;
import Modelo.ProductoMenu;
import Modelo.Reserva;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo alejandro chavarro y juan david villegas
 */

public class CineGUI extends javax.swing.JFrame {
    
    private ControladorCine controlador;
    private ArrayList<FuncionCine> funcionesEnCombo;
    private ArrayList<ProductoMenu> productosEnPantalla;
    private Reserva reservaActual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CineGUI.class.getName());

    /**
     * Creates new form CineGUI
     */
    public CineGUI() {
        initComponents();
        setLocationRelativeTo(null);
        txtAreaResumen.setText("Resumen de la compra...");
    }
    
    public void setControlador(ControladorCine controlador) {
    this.controlador = controlador;
    }
    
    public void mostrarFunciones(ArrayList<FuncionCine> funciones) {
    this.funcionesEnCombo = funciones;

    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    for (FuncionCine f : funciones) {
        
        String titulo = f.getPelicula().getTitulo();
        if (f.getCodigo().equals("F2")) {
            titulo = titulo + " (3D)";
        }
        model.addElement(f.getCodigo() + " - " + f.getPelicula().getTitulo());
    }

    comboFunciones.setModel(model);

    if (!funciones.isEmpty()) {
        comboFunciones.setSelectedIndex(0);
        actualizarLabelDisponibilidad();
    } else {
        lblDisponibilidad.setText("Asientos disponibles: 0");
    }
}
    
    public void mostrarMenu(ArrayList<ProductoMenu> productos) {
    this.productosEnPantalla = productos;

    if (productos.size() > 0) {
        ProductoMenu p1 = productos.get(0);
        chkProd1.setText(p1.getCodigo() + " - " + p1.getNombre());
        chkProd1.setSelected(false);
    }

    if (productos.size() > 1) {
        ProductoMenu p2 = productos.get(1);
        chkProd2.setText(p2.getCodigo() + " - " + p2.getNombre());
        chkProd2.setSelected(false);
    }

    if (productos.size() > 2) {
        ProductoMenu p3 = productos.get(2);
        chkProd3.setText(p3.getCodigo() + " - " + p3.getNombre());
        chkProd3.setSelected(false);
    }
}
    
    private String obtenerCodigoFuncionSeleccionada() {
    int indice = comboFunciones.getSelectedIndex();
    if (indice < 0 || funcionesEnCombo == null || indice >= funcionesEnCombo.size()) {
        return null;
    }
    return funcionesEnCombo.get(indice).getCodigo();
}

private ArrayList<String> obtenerCodigosProductosSeleccionados() {
    ArrayList<String> codigos = new ArrayList<>();

    if (productosEnPantalla == null) {
        return codigos;
    }

    if (chkProd1.isSelected() && productosEnPantalla.size() > 0) {
        codigos.add(productosEnPantalla.get(0).getCodigo());
    }
    if (chkProd2.isSelected() && productosEnPantalla.size() > 1) {
        codigos.add(productosEnPantalla.get(1).getCodigo());
    }
    if (chkProd3.isSelected() && productosEnPantalla.size() > 2) {
        codigos.add(productosEnPantalla.get(2).getCodigo());
    }

    return codigos;
}

    private void actualizarLabelDisponibilidad() {
    if (controlador == null) {
        return;
    }

    String codigoFuncion = obtenerCodigoFuncionSeleccionada();
    if (codigoFuncion == null) {
        lblDisponibilidad.setText("Asientos disponibles: 0");
        return;
    }

    int disponibles = controlador.obtenerDisponibilidadFuncion(codigoFuncion);
    lblDisponibilidad.setText("Asientos disponibles: " + disponibles);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblFuncion = new javax.swing.JLabel();
        comboFunciones = new javax.swing.JComboBox<>();
        lblDisponibilidad = new javax.swing.JLabel();
        lblCantidadBoletos = new javax.swing.JLabel();
        txtCantidadBoletos = new javax.swing.JTextField();
        lblMenu = new javax.swing.JLabel();
        chkProd1 = new javax.swing.JCheckBox();
        chkProd2 = new javax.swing.JCheckBox();
        chkProd3 = new javax.swing.JCheckBox();
        lblCodigoReserva = new javax.swing.JLabel();
        txtCodigoReserva = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizarTelefono = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResumen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Sistema de Reservas Cine UAO");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre cliente: ");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDocumento.setText("Documento");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono");

        lblFuncion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuncion.setText("Funcion");

        comboFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDisponibilidad.setText("Asientos disponibles: - ");

        lblCantidadBoletos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantidadBoletos.setText("Cantidad de boletos:");

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMenu.setText("Menu del cine:");

        chkProd1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkProd1.setText("Producto 1");

        chkProd2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkProd2.setText("Producto 2");

        chkProd3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkProd3.setText("Producto 3");

        lblCodigoReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigoReserva.setText("Codigo reserva: ");

        btnReservar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar reserva");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizarTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarTelefono.setText("Actualizar telefono cliente");
        btnActualizarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTelefonoActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtAreaResumen.setColumns(20);
        txtAreaResumen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAreaResumen.setRows(5);
        txtAreaResumen.setText("Resumen de la compra...");
        jScrollPane1.setViewportView(txtAreaResumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantidadBoletos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblDocumento)
                            .addGap(41, 41, 41)
                            .addComponent(txtDocumento))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReservar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkProd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkProd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkProd3))
                    .addComponent(lblMenu)
                    .addComponent(lblDisponibilidad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFuncion)
                        .addGap(38, 38, 38)
                        .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addGap(59, 59, 59)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncion)
                    .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblDisponibilidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBoletos)
                    .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProd1)
                    .addComponent(chkProd2)
                    .addComponent(chkProd3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoReserva)
                    .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizarTelefono)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
    try {
        String nombre = txtNombre.getText();
        String documento = txtDocumento.getText();
        String telefono = txtTelefono.getText();
        int cantidadBoletos = Integer.parseInt(txtCantidadBoletos.getText());
        String codigoFuncion = obtenerCodigoFuncionSeleccionada();
        ArrayList<String> codigosProductos = obtenerCodigosProductosSeleccionados();

        if (nombre.isEmpty() || documento.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar los datos del cliente.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Reserva reserva = controlador.crearReservaDesdeVista(
                nombre, documento, telefono,
                codigoFuncion, cantidadBoletos, codigosProductos);
        
        reservaActual = reserva; 

        txtCodigoReserva.setText(reserva.getCodigoReserva());
        txtAreaResumen.setText(controlador.generarResumenReserva(reserva));
        actualizarLabelDisponibilidad();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La cantidad de boletos debe ser un número entero.",
                "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    String codigo = txtCodigoReserva.getText();
    if (codigo == null || codigo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe indicar el código de la reserva a eliminar.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean eliminado = controlador.eliminarReservaDesdeVista(codigo.trim());
    if (eliminado) {
        JOptionPane.showMessageDialog(this, "Reserva eliminada correctamente.");
        txtAreaResumen.setText("Reserva eliminada.");
        actualizarLabelDisponibilidad();
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró una reserva con ese código.",
                "Información", JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTelefonoActionPerformed
    String documento = txtDocumento.getText();
    String nuevoTel = txtTelefono.getText();
    if (documento == null || documento.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe indicar el documento del cliente a actualizar.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    String mensaje = controlador.actualizarTelefonoCliente(documento.trim(), nuevoTel);
    JOptionPane.showMessageDialog(this, mensaje);
    
    if (reservaActual != null) {
        txtAreaResumen.setText(controlador.generarResumenReserva(reservaActual));
    }//GEN-LAST:event_btnActualizarTelefonoActionPerformed
}
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtNombre.setText("");
    txtDocumento.setText("");
    txtTelefono.setText("");
    txtCantidadBoletos.setText("");
    txtCodigoReserva.setText("");
    chkProd1.setSelected(false);
    chkProd2.setSelected(false);
    chkProd3.setSelected(false);
    txtAreaResumen.setText("Resumen de la compra...");
    actualizarLabelDisponibilidad();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Cine cine = new Cine();

            CineGUI vista = new CineGUI();

            ControladorCine controlador = new ControladorCine(cine, vista);

            vista.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTelefono;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JCheckBox chkProd1;
    private javax.swing.JCheckBox chkProd2;
    private javax.swing.JCheckBox chkProd3;
    private javax.swing.JComboBox<String> comboFunciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCodigoReserva;
    private javax.swing.JLabel lblDisponibilidad;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaResumen;
    private javax.swing.JTextField txtCantidadBoletos;
    private javax.swing.JTextField txtCodigoReserva;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
